FROM funcapi/base:alpine-3.7

RUN apk add --no-cache libxml2 libxslt libevent libffi glib ncurses readline \
        openssl yaml zlib curl mariadb-libs libpq ruby ruby-io-console ruby-bundler \
        ruby-bigdecimal
